"""Page 7 — How the System Learns (anomaly_rca / Sreeja Katta)."""
import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).parent.parent.parent))
sys.path.insert(0, str(Path(__file__).parent.parent))

import streamlit as st
from components.data_loader import (
    load_prevention_summary,
    load_root_cause_breakdown,
    load_policy_registry,
    load_ifs_distribution,
)
from components.charts import (
    root_cause_donut,
    root_cause_cost_bar,
    policy_source_bar,
    ifs_histogram,
)

st.set_page_config(page_title="How the System Learns — PBCP", layout="wide")
st.title("How the System Learns")
st.caption(
    "Every bad job teaches the system a new rule — so the next similar job gets caught before it wastes money · "
    "Owner: Sreeja Katta"
)

summary  = load_prevention_summary()
rc_df    = load_root_cause_breakdown()
pol_df   = load_policy_registry()
ifs_df   = load_ifs_distribution()

# -- KPI row ----------------------------------------------------------------
c1, c2, c3, c4, c5 = st.columns(5)
c1.metric("IBD-Flagged Runs",      f"{summary['n_ibd']:,}",
          help="Runs where IFS < 0.65 — intent-behavior divergence detected")
c2.metric("Feedback Policies",     f"{summary['n_feedback_generated']:,}",
          help="New PolicySuggestions generated from recurring anomaly patterns")
c3.metric("Mean IFS (IBD)",        f"{summary['mean_ifs']:.3f}",
          help="Average IFS score among flagged IBD workloads")
c4.metric("Est. Cost Impact",      f"${summary['total_cost_impact']:,.0f}",
          help="Estimated waste from IBD workloads (25% of potential cost)")
learned_n = len(pol_df[pol_df["source"] == "learned"]) if not pol_df.empty else 0
c5.metric("Learned Policies",      str(learned_n),
          help="Policies in registry with source='learned'")

st.divider()

# -- Row 1: root cause breakdown + cost impact ------------------------------
col_l, col_r = st.columns(2)

with col_l:
    st.subheader("Root Cause Breakdown")
    st.caption(
        "Inferred from the lowest IFS sub-score: "
        "resource_alignment → over_provisioned, "
        "util_alignment → idle_cluster, "
        "duration_alignment → runaway_job, "
        "type_alignment → type_mismatch."
    )
    if not rc_df.empty:
        st.plotly_chart(root_cause_donut(rc_df), use_container_width=True)
    else:
        st.info("No IBD records found in database.")

with col_r:
    st.subheader("Mean Cost Impact by Root Cause")
    st.caption("Average estimated waste per run, broken down by the primary failure mode.")
    if not rc_df.empty:
        st.plotly_chart(root_cause_cost_bar(rc_df), use_container_width=True)

st.divider()

# -- Row 2: policy registry + IFS of IBD workloads -------------------------
col_l, col_r = st.columns(2)

with col_l:
    st.subheader("Policy Registry — Source Breakdown")
    st.caption(
        "Builtin policies are hand-authored rules. "
        "Learned policies are generated by the feedback loop when a pattern recurs ≥ 3 times "
        "with confidence ≥ 0.60."
    )
    if not pol_df.empty:
        st.plotly_chart(policy_source_bar(pol_df), use_container_width=True)

with col_r:
    st.subheader("IFS Distribution — IBD Workloads Only")
    st.caption("IFS scores for workloads below the IBD threshold (IFS < 0.65).")
    ibd_ifs = ifs_df[ifs_df["ifs"] < 0.65] if not ifs_df.empty else ifs_df
    if not ibd_ifs.empty:
        st.plotly_chart(ifs_histogram(ibd_ifs), use_container_width=True)
    else:
        st.info("No IBD records found.")

st.divider()

# -- Root cause detail table ------------------------------------------------
st.subheader("Root Cause Detail")
if not rc_df.empty:
    st.dataframe(
        rc_df.rename(columns={
            "root_cause": "Root Cause", "n": "Count",
            "mean_ifs": "Mean IFS", "mean_cost_impact": "Mean Cost Impact ($)",
        }),
        use_container_width=True, hide_index=True,
    )

st.divider()

# -- Policy registry table --------------------------------------------------
st.subheader("Active Policy Registry")
st.caption("All policies currently governing workload submissions.")
if not pol_df.empty:
    display_cols = ["policy_id", "workload_type", "source", "action", "confidence"]
    if "description" in pol_df.columns:
        display_cols.append("description")
    st.dataframe(
        pol_df[display_cols].rename(columns={
            "policy_id": "Policy ID", "workload_type": "Workload Type",
            "source": "Source", "action": "Action",
            "confidence": "Confidence", "description": "Description",
        }),
        use_container_width=True, hide_index=True,
    )

# -- How it works callout ---------------------------------------------------
st.divider()
with st.expander("How the Prevention Feedback Loop works"):
    st.markdown("""
**Step 1 — Measure:** `IFSCalculator` scores every completed run (0–1). Runs below
θ = 0.65 are flagged as Intent-Behavior Divergences (IBD).

**Step 2 — Diagnose:** `_infer_root_cause()` looks at the four IFS sub-scores
(type, utilization, duration, resource alignment) and picks the worst one as the
primary failure mode.

**Step 3 — Learn:** When a (workload_type, root_cause) pattern appears ≥ 3 times,
`AnomalyPreventionFeedback` computes a confidence score (= min(count / 10, 0.95))
and generates a `PolicySuggestion`.

**Step 4 — Prevent:** If confidence ≥ 0.60 and no policy for this pattern already
exists, the suggestion is added to `PolicyRegistry` with `source="learned"`.
The next time a similar workload is submitted, the policy fires *before* resources
are created — turning a past anomaly into a future prevention.
""")
